default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DB_USER") %>
  password: <%= ENV.fetch("RAILS_DB_PASS") %>
  database: scorer

development:
  <<: *default
  host: <%= ENV.fetch("RAILS_DB_HOST") %>

test:
  <<: *default

production:
  <<: *default
  adapter: mysql2
