name: Run ruby tests

on:
  push:
    branches:
      - '*'
 
jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: no
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
            MYSQL_DATABASE: scorer_dev
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 6 --retry 3
        bundle exec rake
      env:
        RAILS_ENV: development
        RAILS_DB_HOST: localhost
        RAILS_DB_USER: user
        RAILS_DB_PASS: user_password
